# Generated by Django 2.1.7 on 2019-05-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contens', models.CharField(max_length=500)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='crudapp.Comment')),
                ('reply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='crudapp.Comment')),
            ],
        ),
    ]
