# Generated by Django 2.1.7 on 2019-05-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_commentreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='commentreply',
            old_name='contens',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='reply_id',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='crudapp.Comment'),
        ),
    ]
